### PR TITLE
Support scalajs-react 2.0.0 (also for scala 3)

### PR DESCRIPTION
**Pull request by oyvindberg**

### CODE REVIEW

**Comment by oyvindberg** [comment]
Pending https://github.com/japgolly/scalajs-react/issues/932

**Comment by oyvindberg** [comment]
demo updates for Scala 3 https://github.com/ScalablyTyped/ScalaJsReactDemos/pull/12

**Comment by oyvindberg** [comment]
snapshot version with support for 2.0.0 final: `1.0.0-beta36+35-09aed2df-SNAPSHOT`. cc @rpiaggio

**Comment by mariussoutier** [comment]
Is there a way to use newer versions of ScalablyTyped and stay on scalajs-react 1.7.x at the same time? Eviction errors in sbt seem to suggest otherwise.

**Comment by oyvindberg** [comment]
No, sorry. ST is built in an integration project-like , roll-forward only style. Anything else is too much work.

You can build it yourself rather easily by checking out the tag of the second latest release, cherry-pick the sbt 1.6 commit on top and SBT publishLocal.

**Comment by mariussoutier** [comment]
Ok thanks.

**Pull request merged**
