### PR TITLE
Bump sbt to 1.4.x (Fix #168)

### LINKED ISSUE #168: Compiled with sbt 1.4.0 line?
I tried to use `sbt-coverter` with sbt `1.4.0-M1` and it seems to have problem with classpath:

```
webChart/compile
[info] Total time: 1 sec
[error] stack trace is suppressed; run last webChart / stInternalZincCompiler for the full output
[error] (webChart / stInternalZincCompiler) java.lang.NoSuchMethodError: xsbti.compile.CompileOptions.withClasspath([Ljava/io/File;)Lxsbti/compile/CompileOptions;
[error] Total time: 1 s, completed Jun 17, 2020, 3:51:23 PM
sbt:Anduin Design> 

```

I have tried to update sbt myself for `sbt-converter` but getting into the internal `ZincCompiler` looks a bit harder than I thought.

### PR DESCRIPTION
**Pull request by oyvindberg**
Will merge after 1.4.0 final

### CODE REVIEW

**Comment by nafg** [comment]
Once 1.4.0 is out will it be possible to only support 1.4.x, or will you need to maintain a 1.3.x line temporarily in parallel with a 1.4.x line?

**Comment by oyvindberg** [comment]
@nafg with this approach it'll be 1.4.x only, I think that's fine for now because if you're already on 1.3 the upgrade should be simple to 1.4. and if it's a problem I'm sure you can stay on an old version of ST as well.

Hopefully though there is a better solution, I'll ask around a bit

**Comment by nafg** [comment]
One option is to put the sbt minor version in the artifact name, changing
the plugins.sbt snippet accordingly, and then if you need to backport
something for sbt 1.3.x you can just do it from a branch.

**Comment by oyvindberg** [comment]
@nafg yeah that would definitely be possible, though I would of course prefer not to. With that level of effort I'd rather spend it finding a better way to use sbt :)

**Comment by hepin1989** [comment]
SBT 1.4.0-RC2 is out:)

**Pull request merged**
