### PR TITLE
Predictable module names (fixes #469)

### LINKED ISSUE #469: Unexpected mod naming for antd
Antd 4.22.3 has `lib/pagination/Select.d.ts` and `lib/select/index.d.ts`.

The former is being converted to `typings.antd.selectMod` and the later `typings.antd.libSelectMod`.

### PR DESCRIPTION
**Pull request by oyvindberg**
## Problem

It's almost impossible to map Javascript module names to ST object/package names. 

There is a 1-1 correspondence, but it's impossible to understand. Let's finally fix this mistake!

I know this will lead to "uglier"/longer module names, this has been discussed various times in the past, but the encoding *needs* to become easier to understand. 

## Keep old behavior 

add `stShortModuleNames` (for sbt plugin) and `--shortModuleNames` for CLI which reverts to old behaviour.

Note that this old behaviour is deprecated. I don't intend to remove it for a long while, but I won't put any effort into maintaining it either.

## Example 

Here is a typical example of what it'll look like - see how clearly you can see the hierarchy even though it's flattened.

Screenshot 2022-10-13 at 14 57 55

### CODE REVIEW

**Comment by oyvindberg** [comment]
One possible problem is that this might trigger windows long file name errors, those were somewhat common in the past. I think if that happens let's rather compress the file names on windows and keep the package names correct.

**Comment by nafg** [comment]
With class files the packages will always correspond to directories so not sure that is an option

**Comment by oyvindberg** [comment]
@nafg to gauge the problem I wrote a script to traverse all the jar files for a full CI build, looking for the longest class files. The longest is a trait produced from the fake string literals:

```
typings/octokitPluginRestEndpointMethods/octokitPluginRestEndpointMethodsStrings$DELETE$u0020SlashreposSlashLeftcurlybracketownerRightcurlybracketSlashLeftcurlybracketrepoRightcurlybracketSlashactionsSlashcachesLeftcurlybracketQuestionmarkkeyCommarefRightcurlybracket.class
```

 This will blow up the windows path budget in any case, weighing in at 274 chars. On the bright side, this should be gone after #487, so let's dig up the longest class class file name after removing those of fake strings:
```
typings/officeUiFabricReact/libComponentsPickersPeoplePickerPeoplePickerItemsPeoplePickerItemDottypesMod$IPeoplePickerItemSelectedSubComponentStyles$IPeoplePickerItemSelectedSubComponentStylesMutableBuilder$.class
```
214 chars. Will very likely fail on windows, given that there is a semi-long prefix added to this.

If we change the naming pattern for the builder class, it could come out like this instead:
```
typings/officeUiFabricReact/libComponentsPickersPeoplePickerPeoplePickerItemsPeoplePickerItemDottypesMod$IPeoplePickerItemSelectedSubComponentStyles$MutableBuilder$.class
```

That's 171 chars. borderline possible to compile on windows.

**Comment by FabioPinheiro** [comment]
Thanks, @oyvindberg  for pointing out where the changes come from.
I tested the flag and `stShortModuleNames` keeps all the code compiling with no change (on my project).
Either way, I will probably change the code and not use the flag.

**Pull request merged**
