### PR TITLE
Allow inherting js.Promise/js.Thenable instead of those in typings.std

### PR DESCRIPTION
**Pull request by exoego**
Addresses https://gitter.im/ScalablyTyped/community?at=5f2a5e1e45cf645e4a0d4318

### CODE REVIEW

**Comment by oyvindberg** [comment]
Hey there @exoego , thanks for you participation :+1: 

So I wanted to get back to you to see if this issue was already solved, because I couldn't really reproduce it.
I did give a bit of wrong info on gitter - the converter code already is meant to always translate `typings.std.Promise` to `js.Promise`, regardless of `stUseScalaJsDom`. The implementation of that is exactly in these lines you're touching here.

Can you help me reproduce this first, and then we can dig into the fix?

For instance if you could 1) verify you use latet beta version, 2) verify the issue is still there, and 3) report what these commands say for your project:
```
sbt:slinkydemos> antd/stConversionOptions
[info] ConversionOptions(true,Slinky,Name(typings),NoneExcept(List()),IArray(es6),AllExcept(ArrayBuffer(TsIdentLibrarySimple(std), TsIdentLibrarySimple(prop-types), TsIdentLibrarySimple(react))),Set(TsIdentLibrarySimple(typescript)),Set(List(typescript)),Versions(Scala(2.13.2),ScalaJs(1.1.0)),org.scalablytyped,NoneExcept(List()))
sbt:slinkydemos> antd/Compile/npmDependencies
[info] * (react,16.13.1)
[info] * (react-dom,16.13.1)
[info] * (@types/react,16.9.42)
[info] * (@types/react-dom,16.9.8)
[info] * (csstype,2.6.11)
[info] * (@types/prop-types,15.7.3)
[info] * (antd,4.5.1)
```
(feel free to redact the library list if necessary, but keep at least the exact version of the library where you see the wrong promise)

**Comment by exoego** [comment]
Hmm, as far as I tested, `"sbt-converter" % "1.0.0-beta24"` still converts TypeScript `Promise<T>` into `typings.std.Promise[T]`.

Given https://github.com/elastic/elasticsearch-js/blob/ba39e8a440526f3d5a06eba9ac67c9e3fcd5b44e/lib/Transport.d.ts#L121
Then
```scala
package typings.elasticElasticsearch.transportMod

import typings.std.Promise
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@js.native
trait TransportRequestPromise[T] extends Promise[T] {
  def abort(): Unit = js.native
}
```

**Comment by oyvindberg** [comment]
Aha! Now I get what happens. This should probably go into the docs, I just thought it would be pretty infrequent.

The converter will rewrite `typings.std.Promise` to `js.Promise` as long as it's not in an inheritance clause, which is what you have here.

The reason is that the [scala.js pipeline](https://github.com/ScalablyTyped/Converter/blob/master/importer-portable/src/main/scala/org/scalablytyped/converter/internal/importer/Phase2ToScalaJs.scala#L80-L82) of the conversion needs to know the complete types of all the members of all parent classes to determine if a given member of a class is an override and if it has the same erasure.

Once a reference is rewritten to a class defined elsewhere, in normal scala, the converter doesn't have any means to lookup a class file and determine what that class looks like.

How to fix it for `js.Promise` specifically:
- [this line](https://github.com/ScalablyTyped/Converter/blob/master/importer-portable/src/main/scala/org/scalablytyped/converter/internal/importer/ImportType.scala#L54) specifies what the typescript type for `Promise` should be rewritten to in inheritance and outside, respectively. you can change the former to match the latter
- Add entries for `js.Promise` and `js.Thenable` [here](https://github.com/ScalablyTyped/Converter/blob/master/scalajs/src/main/scala/org/scalablytyped/converter/internal/scalajs/ScalaJsClasses.scala). One potential complication is that I see the definition of `Promise` uses scala features (variance, lower bounds) not implemented in the local Scala [AST](https://github.com/ScalablyTyped/Converter/blob/master/scalajs/src/main/scala/org/scalablytyped/converter/internal/scalajs/tree.scala), so I guess just simplify.
- probably needs a [test](https://scalablytyped.org/docs/devel/about#importertesthttpsgithubcomscalablytypedconverterblobmasterimportersrctestscalaorgscalablytypedconverterinternalimporterimportertestscala) where you define typescript types extending `Promise<T>` and (say) `Promise<number>` with explicitly defined definitions of `then/catch` to see that scala compilation doesnt fail, typically with the complaint that methods have the same erasure.

It might be a bit more work than you had in mind maybe, but I suppose there's a reason why I hadnt spent more time on this :)

**Comment by oyvindberg** [comment]
Alright, this looks excellent now. I'll touch it up slightly to add the `then` and `catch` members in the scala.js definitions of the types and then release it within a few days :+1:

**Comment by oyvindberg** [comment]
Of course there were more complications here, it doesn't have a zero argument constructor.
```
[error] 2020-08-24T03:10:08.735169Z Phase3Compile.scala:149 err Compiling std (2563 Scala sources)
Non-compiled module 'compiler-bridge_2.13' for Scala 2.13.3. Compiling...
  Compilation completed in 7.244s.
[E] [E1] src/main/scala/typingsSlinky/std/global/Promise.scala:12:14
[E]      not enough arguments for constructor Promise: (executor: scala.scalajs.js.Function2[scala.scalajs.js.Function1[T | scala.scalajs.js.Thenable[T], _], scala.scalajs.js.Function1[Any, _], _]): scala.scalajs.js.Promise[T].
[E]      Unspecified value parameter executor.
[E]      L12:   extends js.Promise[T] {
[E]                        ^
[E] src/main/scala/typingsSlinky/std/global/Promise.scala: L12 [E1]
Compiled std (21472ms)
[E] Failed to compile 'std'
 [id => std, thread => 1, phase => build, flavour => SlinkyFlavour]
```

I *think* I can say that any *trait* can extend `js.Promise`, but not classes. Will verify and open a follow-up PR

**Pull request merged**
