### PR TITLE
Remote cache

### PR DESCRIPTION
**Pull request by oyvindberg**
This makes demos more demoable for now, it'll have to be expanded for third party use cases later

[asciicast](https://asciinema.org/a/t2PGPEXmWXgHplSx4MUIziikT)

docs so far:

### Remote cache

The whole conversion process is unfortunately pretty slow. To alleviate this there is an option to use a remote cache,
where `rsync` transfers all necessary files to a remote server where it can be pulled later. 
It's like a maven repo with transient libraries, where if they are not found the plugin will automatically rebuild them locally.

First you need to set it up:
```scala
Global / stRemoteCache := RemoteCache.Rsync(
  push = "user@server.com:/path/to/st/cache", 
  pull = new java.net.URI("https://server.com/path/to/st/cache")
)
```

The first parameter specifies where files will be uploaded, and the second how to reach the files through http. 
Pushing requires access through ssh keys, while typically anybody can pull files.

To push files run `stPublishCache`. Pulling will be done automatically.

If `rsync` is not suitable for your particular use case feel free to get in touch if you want to implement another scheme,
 it shouldn't be hard.

### CODE REVIEW

**Comment by an-tex** [comment]
Good stuff! S3 API compatibility might make sense too? Then you could hookup AWS/Digitialocean/minio in a breeze for the upload. ReadOnly clients could still go through HTTP. I could look into it next week. Would deff be nice to speed up compilation between local devs and ci

**Comment by oyvindberg** [comment]
Yes @an-tex , that's a very good idea. My only consideration for that it should be implementable with few external dependencies to avoid conflicts in sbts class loader

**Comment by an-tex** [comment]
I see. Alpakka which pulls Akka is not an option then I guess ;) The 2nd easiest option would be the [official amazon s3-java sdk](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/pom.xml). Last resort would be to use any existing http client and building the request ourselves. Not too bad, it's REST after all, just would need to sign the request manually. What you reckon?

**Comment by oyvindberg** [comment]
@an-tex the official libs are probably just fine, it doesnt seem to have so many dependencies and they are all java:
```
$ cs resolve com.amazonaws:aws-java-sdk-s3:1.11.827
com.amazonaws:aws-java-sdk-core:1.11.827:default
com.amazonaws:aws-java-sdk-kms:1.11.827:default
com.amazonaws:aws-java-sdk-s3:1.11.827:default
com.amazonaws:jmespath-java:1.11.827:default
com.fasterxml.jackson.core:jackson-annotations:2.6.0:default
com.fasterxml.jackson.core:jackson-core:2.6.7:default
com.fasterxml.jackson.core:jackson-databind:2.6.7.3:default
com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:2.6.7:default
commons-codec:commons-codec:1.11:default
commons-logging:commons-logging:1.2:default
joda-time:joda-time:2.8.1:default
org.apache.httpcomponents:httpclient:4.5.9:default
org.apache.httpcomponents:httpcore:4.4.11:default
software.amazon.ion:ion-java:1.0.2:default
```

**Comment by an-tex** [comment]
Cool sounds good. Should I open a separate PR?

**Comment by oyvindberg** [comment]
That would be great! I'm sure we'll have to iterate a bit on this design, but I'll go ahead and merge this first version now :+1:

**Pull request merged**
