### PR TITLE
Japgolly builders

### PR DESCRIPTION
**Pull request by oyvindberg**
Finally sat down and ported the scalajs-react flavour to use builders as well

### todo: 
- deduplication of code
- testing that it actually works

### CODE REVIEW

**Comment by oyvindberg** [comment]
The diff is unnecessarily big, but if you're dropping by for instance [this file](https://github.com/ScalablyTyped/Converter/pull/177/files?diff=split&w=1#diff-3dd4013410c4b27c4d4ae165321f9f35) is a decent example of before/after

**Comment by an-tex** [comment]
I'm getting many compilation errors in the tasks:
```
[error] (service1UiClient / stImport) FromFolder(InFolder(/Users/andreas/dev/reference/service1/ui/client/target/scala-2.12/scalajs-bundler/main/node_modules/@types/react),TsIdentLibrarySimple(react)) -> Right(Compilation failed)
[error] (service1UiClient / ssExtractDependencies) FromFolder(InFolder(/Users/andreas/dev/reference/service1/ui/client/target/scala-2.12/scalajs-bundler/main/node_modules/@types/react),TsIdentLibrarySimple(react)) -> Right(Compilation failed)
```

like this:

```
[error] ZincCompiler.scala:205 [Error] /Users/andreas/dev/reference/service1/ui/client/target/streams/_global/stImport/_global/streams/sources/r/react/src/main/scala/typings/StBuildingComponent.scala:16: type mismatch;
[error]  found   : StBuildingComponent.this.type (with underlying type typings.StBuildingComponent[R])
[error]  required: AnyRef
[error] Note that StBuildingComponent extends Any, not AnyRef.
[error] Such types can participate in value classes, but instances
[error] cannot appear in singleton types or in reference comparisons.
[...]
[error] ZincCompiler.scala:205 [Error] /Users/andreas/dev/reference/service1/ui/client/target/streams/_global/stImport/_global/streams/sources/r/react/src/main/scala/typings/react/components/Profiler.scala:26: type mismatch;
[error]  found   : Builder.this.type (with underlying type typings.react.components.Profiler.Builder)
[error]  required: AnyRef
[error] Note that Builder extends Any, not AnyRef.
[error] Such types can participate in value classes, but instances
[error] cannot appear in singleton types or in reference comparisons.
[...]
[error] ZincCompiler.scala:205 [Error] /Users/andreas/dev/reference/service1/ui/client/target/streams/_global/stImport/_global/streams/sources/r/react/src/main/scala/typings/react/components/Suspense.scala:23: type mismatch;
[error]  found   : Builder.this.type (with underlying type typings.react.components.Suspense.Builder)
[error]  required: AnyRef
[error] Note that Builder extends Any, not AnyRef.
[error] Such types can participate in value classes, but instances
[error] cannot appear in singleton types or in reference comparisons.
```

here's the build.sbt:
```scala
libraryDependencies ++= Seq(
  "com.github.japgolly.scalajs-react" %%% "core" % "1.7.3",
  "com.github.japgolly.scalajs-react" %%% "extra" % "1.7.3",
  "com.github.japgolly.scalacss" %%% "core" % "0.6.1",
  "com.github.japgolly.scalacss" %%% "ext-react" % "0.6.1",
  "org.scala-js" %%% "scalajs-dom" % "1.0.0",
  "io.suzaku" %%% "diode" % "1.1.10",
  "io.suzaku" %%% "diode-react" % "1.1.10.172-antex",
  "com.github.mliarakos.lagomjs" %%% "lagomjs-scaladsl-client" % "0.4.0-1.6.2",
  Dependencies.chimney.value,
)

Compile / npmDependencies ++= Seq(
  "react" -> "16.13.1",
  "react-dom" -> "16.13.1",
  "@types/react" -> "16.9.35",
  "@types/react-dom" -> "16.9.8",
  "antd" -> "4.4.0",
  "css-loader" -> "3.5.3",
  "style-loader" -> "1.2.1",
  "less" -> "3.11.1",
  "less-loader" -> "6.1.0",
  "@fortawesome/fontawesome-svg-core" -> "1.2.29",
  // upgrading causes incomplete generation
  "@fortawesome/react-fontawesome" -> "0.1.8"
) ++ Seq(
  "@fortawesome/free-brands-svg-icons",
  "@fortawesome/pro-light-svg-icons",
  "@fortawesome/pro-solid-svg-icons",
  "@fortawesome/pro-regular-svg-icons",
  "@fortawesome/pro-duotone-svg-icons"
).map(_ -> "5.13.1")

stIgnore ++= List(
  "csstype",
  "@ant-design/icons"
)

version in webpack := "4.43.0"
version in startWebpackDevServer := "3.11.0"
webpackBundlingMode := BundlingMode.LibraryOnly("reference")
webpackConfigFile := Some(baseDirectory.value / "webpack.config.js")
```

Probably I won't have time to look into it any further today but let me know if you need a minimal reproduction then I'll get sth ready next week.

**Comment by oyvindberg** [comment]
Hey there @an-tex . I couldn't immediately reproduce that error. Can you pull/clean/publishLocal this branch and try again with the new snapshot version you'll get please? Justto weed out some possible classes of errors

**Comment by an-tex** [comment]
Cheers mate, will do on Monday

**Comment by oyvindberg** [comment]
I'll go ahead and merge, and we can deal with the compilation problem in a followup if it keeps being a problem :)

**Pull request merged**
