### PR TITLE
Reinstate old source generator plugin for library developers

### PR DESCRIPTION
**Pull request by oyvindberg**

### CODE REVIEW

**Comment by oyvindberg** [comment]
I'll dig up the old documentation and brush it up a bit as well so it's easy to publish libraries based on ScalablyTyped. 

CC @rpiaggio @mushtaq @elkhadirzyad I think you all asked for this at some point

**Comment by rpiaggio** [comment]
Thank you @oyvindberg !

**Comment by mushtaq** [comment]
Thanks! 

I am currently using the `stc` cli for generating libs and publishing them to bintray. `stc` command also prints the library dependency strings which we use in apps.

I guess after this PR, `stc` will put those strings in an sbt plugin and push it to the bintray as well?

**Comment by oyvindberg** [comment]
Maybe i misremembered what you wanted @mushtaq :) It's pretty easy to generate such a plugin, you could probably PR it yourself if you need it.

This is a way to publish independent libraries, where part of them is generated by the converter. 

The generated code is complete for the libraries you specify, while (transitive) dependencies are minimized and included. You would also shade it into another package to avoid name conflicts.

**Comment by mushtaq** [comment]
Np. I will wait for the docs to see if I understand it fully.

**Comment by oyvindberg** [comment]
docs here https://scalablytyped.org/docs/library-developer

**Comment by oyvindberg** [comment]
And example project https://github.com/ScalablyTyped/mobx-slinky

**Pull request merged**
