### PR TITLE
add scalablytyped icon

### PR DESCRIPTION
**Pull request by mvillafuertem**
I have created a simple logo for scalablytyped 

https://github.com/ScalablyTyped/Converter/blob/2c9f575eefd74cfe1f8db65bf13141df626c83b6/README.md

### CODE REVIEW

**Comment by oyvindberg** [comment]
Hey there @mvillafuertem , thanks for this! Sorry I spent a few days before getting to you :)

I like it, it communicates well what it is. A few questions:
- do you have any idea what a small version of it could look like?
- or how it could fit into scalablytyped.org (it currently has an orange theme, but we could certainly change that)
- is it allowed to use the scala logo like this?

**Comment by mvillafuertem** [comment]
Hi @oyvindberg 

I'm glad you like it. 👍 

- I have added some small versions 64x64, 32x32, 16x16
https://github.com/ScalablyTyped/Converter/blob/652452d89afcbda7e0c515072794ba444d65c25d/README.md

-  If you want. I could test scalablytyped.org with a red theme.

- I found this thread talking about this, but I will ask in the scala gitter
https://groups.google.com/g/scala-user/c/bCC-R0FQn1w

**Comment by oyvindberg** [comment]
Great! Let's say that's good enough legally for now, there's no profit anywhere near this project :+1: 

If you feel like it it would be nice if you could experiment a bit with the webpage as well. to start editing it:
```
$ sbt docs/mdoc # this supports --watch so you can leave it running
$ cd website
$ yarn # install deps once
# yarn start
```

I think the colour theme is in a json file or something

**Comment by mvillafuertem** [comment]
scalablytyped

**Comment by oyvindberg** [comment]
That's looks really great @mvillafuertem ! :)

**Comment by oyvindberg** [comment]
I'll go ahead and merge now, it all looks great. if you have more you want to do we can do that in a followup :)

**Pull request merged**
